# Generated by Django 5.1.6 on 2025-02-09 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("displays", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="screencontent",
            options={},
        ),
        migrations.RemoveField(
            model_name="screencontent",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="screencontent",
            name="object_id",
        ),
        migrations.AddField(
            model_name="screencontent",
            name="slide_show",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="displays.slideshow",
            ),
        ),
    ]
